print('='*30)
import matplotlib 
print(matplotlib._version)
#<module 'matplotlib._version' from 'C:\\Users\\ENG-Alhousainy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\
# site-packages\\matplotlib\\_version.py'>
print(matplotlib.__version__)#3.5.3
# import matplotlib.pyplot as plt
# plt.style.use('bmh')
# T=(1,2,3,6,5,8,7,4)
# plt.plot(T)
# import matplotlib.pyplot as plt
# T1=(-4,-2,-1,0,1,2,3,4,5,6,7,8)
# T2=(4,5,8,25,36,40,7,6,3,10,12,21)
# plt.style.use('ggplot')
# plt.plot(T1,T2)
# plt.style.use('bmh')
# plt.plot(T1,T2)
import matplotlib.pyplot as plt
import numpy as np 
T3=np.linspace(0,10)
T4=np.sin(T3)
#plt.plot(T3,T4)
T5=np.cos(T3)
plt.plot(T3,T5)
a=(1,2,3,4,5,6)
b=(3,9,10,12,16,18)
plt.style.use('ggplot')
plt.ylabel('Time')
plt.xlabel('Work')
plt.plot(a,b)
a=(1,2,3,4,5,6)
b=(3,9,10,12,16,18)
ax=plt.axes()
ax.set_xlabel('Time')
ax.set_ylabel('Work')
plt.plot(a,b)
a=(1,2,3,4,5,6)
b=(3,9,10,12,16,18)
ax=plt.axes()
ax.set(xlabel='Time',ylabel='Work')
plt.plot(a,b)
a=(1,2,3,4,5,6)
b=(3,9,10,12,16,18)
plt.style.use('ggplot')
ax=plt.axes()
ax.set(xlabel='Work',ylabel='Time')
plt.plot(a,b,marker='x',markersize=12)
a=np.arange(10)
b=(-1,-2,-3,0,8,4,6,12,15,2)
ax=plt.axes()
plt.style.use('ggplot')
ax.set(xlabel='Work',ylabel='Time')
plt.title('Time/Work Consumptions')
plt.plot(a,b,color='blue',marker='o',markersize=11)
a=np.arange(10)
b=(-1,-2,-3,0,8,4,6,12,15,2)
ax=plt.axes()
plt.style.use('ggplot')
ax.set(xlabel='Work',ylabel='Time')
ax.set_title('Time/Work Consumptions')
plt.plot(a,b,color='blue',marker='o',markersize=12)
a=np.arange(10)
b=(-1,-2,-3,0,8,4,6,12,15,2)
plt.style.use('ggplot')
ax=plt.axes()
ax.set(xlabel='Work',ylabel='Time')
ax.set(title='Time\Work Consumptions')
plt.plot(a,b,color='blue',marker='o',markersize=12)
x=np.arange(0,10,0.005)
y=np.exp(-x/2)*np.sin(2*np.pi*x)
plt.style.use('ggplot')
ax=plt.axes()
ax.set(xlabel='X Axsis',ylabel='Y Axsis')
ax.set(title='Complex Function')
plt.plot(x,y,color='blue',marker='o',markersize=2)
def p1(x): return np.power(x,4)-4*np.power(x,2)+3*x
def p2(x): return np.sin(10*x)*10
ax=plt.axes()
plt.style.use('ggplot')
ax.set(xlabel='X Axsis', ylabel='Y Axsis')
ax.set(title='Two Functions Together')
x=np.linspace(-3,3,1000)
plt.plot(x,p1(x),x,p2(x))
def p1(x): return np.power(x,4)-4*np.power(x,3)+3*x
def p2(x): return np.sin(10*x)*10
def p3(x): return np.cos(5*x)*60
def p4(x): return np.exp(np.power(x,5)/2)
x=np.linspace(-1,1,1000)
ax=plt.axes()
plt.style.use('ggplot')
ax.set(xlabel='X Axsis' ,ylabel='Y Axsis')
ax.set(title ='Complex Functions Together')
plt.plot(x,p1(x),x,p2(x),x,p3(x),x,p4(x))
x=np.arange(0,10,0.005)
ax=plt.axes()
plt.style.use('bmh')
ax.set(xlabel='X Axsis',ylabel='Y Axsis')
ax.set(title ='Drwing Different Lines')
plt.plot(x,x+0,linestyle='solid')
plt.plot(x,x+1,linestyle='-')
plt.plot(x,x+4,linestyle='dashed')
plt.plot(x,x+5,linestyle='--')
plt.plot(x,x+8,linestyle='dashdot')
plt.plot(x,x+9,linestyle='-.')
plt.plot(x,x+12,linestyle='dotted')
plt.plot(x,x+13,linestyle=':')
x=np.arange(0,10,0.005)
ax= plt.axes()
ax.set(xlabel='X Axsis' ,ylabel='Y Axsis')
ax.set(title = 'Different Between Lines')
plt.plot(x,x+0,'b--')
plt.plot(x,x+3,'o-')
plt.plot(x,x+6,'r-.')
plt.plot(x,x+9,'g:')
x=np.arange(0,10,0.005)
ax=plt.axes()
plt.plot('ggplot')
ax.set(title='Line Width')
ax.set(xlabel='X Axsis' , ylabel='Y Axsis')
plt.plot(x,x+0,'b--',linewidth=1)
plt.plot(x,x+3,'g-',linewidth=5)
plt.plot(x,x+6,'r-',linewidth=9)
plt.plot(x,x+9,'o-',linewidth=13)
x=np.arange(0,10,0.005)
ax=plt.axes()
plt.plot('bmh')
ax.set(xlabel='X Axsis',ylabel='Y Axsis')
ax.set(title='Different Colors')
plt.plot(x,x+0,color='r',marker='o',markersize=2)
plt.plot(x,x+2,color='g',marker='o',markersize=2)
plt.plot(x,x+4,color='b',marker='o',markersize=2)
plt.plot(x,x+6,color='m',marker='o',markersize=2)
plt.plot(x,x+8,color='y',marker='o',markersize=2)
plt.plot(x,x+10,color='k',marker='o',markersize=2)
plt.plot(x,x+12,color='w',marker='o',markersize=2)
plt.plot(x,x+14,color='c',marker='o',markersize=2)
x=np.arange(0,10,0.5)
ax=plt.axes()
plt.xlabel('X Axsis')
ax.set_ylabel('Y Axsis')
ax.set_title('Different Type From Marker')
plt.plot('ggplot')
plt.plot(x,x+0,'-')
plt.plot(x,x+5,'o')
plt.plot(x,x+10,'-o')
x=np.arange(0,10,0.5)
ax=plt.axes()
plt.style.use('ggplot')
plt.xlabel('X Axsis')
ax.set_ylabel('Y Axsis')
ax.set(title='Another Deifferent Types From Lines')
x=np.arange(0,10,0.5)
ax=plt.axes()
plt.style.use('ggplot')
plt.xlabel('X Axsis')
ax.set_ylabel('Y Axsis')
ax.set(title='Another Deifferent Types From Lines')
plt.plot(x,x+0,'--')
plt.plot(x,x+1,'1')
plt.plot(x,x+4,'2')
plt.plot(x,x+20,'3')
plt.plot(x,x+25,'4')
plt.plot(x,x+3,'^')
plt.plot(x,x+6,'.')
plt.plot(x,x+9,':')
plt.plot(x,x+12,'<')
plt.plot(x,x+15,'>')
plt.plot(x,x+18,'x')
plt.plot(x,x+27,'8')
plt.plot(x,x+29,'s')
plt.plot(x,x+31,'P')
plt.plot(x,x+33,'p')
x=np.arange(0,10,0.5)
ax=plt.axes()
plt.style.use('ggplot')
ax.set_ylabel('Y Axsis')
ax.set_xlabel('X Axsis')
ax.set(title='Different Lines With Colors')
plt.plot(x,x+0,'r*')
plt.plot(x,x+3,'gh')
plt.plot(x,x+6,'bx')
plt.plot(x,x+9,'y+')
